import pxr.UsdPhysics._usdPhysics
import typing
import Boost.Python
import pxr.Usd
import pxr.UsdGeom
import pxr.UsdPhysics

__all__ = [
    "ArticulationRootAPI",
    "CollisionAPI",
    "CollisionGroup",
    "DistanceJoint",
    "DriveAPI",
    "FilteredPairsAPI",
    "FixedJoint",
    "GetStageKilogramsPerUnit",
    "Joint",
    "LimitAPI",
    "MassAPI",
    "MaterialAPI",
    "MeshCollisionAPI",
    "PrismaticJoint",
    "RevoluteJoint",
    "RigidBodyAPI",
    "Scene",
    "SetStageKilogramsPerUnit",
    "SphericalJoint",
    "StageHasAuthoredKilogramsPerUnit",
    "Tokens"
]


class ArticulationRootAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class CollisionAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateCollisionEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateSimulationOwnerRel(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollisionEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSimulationOwnerRel(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class CollisionGroup(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateFilteredGroupsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollidersCollectionAPI(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFilteredGroupsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class DistanceJoint(Joint, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateMaxDistanceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateMinDistanceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMaxDistanceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMinDistanceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class DriveAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateDampingAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateMaxForceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateStiffnessAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateTargetPositionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateTargetVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateTypeAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDampingAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMaxForceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStiffnessAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargetPositionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargetVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPhysicsDriveAPIPath(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class FilteredPairsAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateFilteredPairsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFilteredPairsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class FixedJoint(Joint, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class Joint(pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateBody0Rel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBody1Rel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBreakForceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBreakTorqueAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateCollisionEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateExcludeFromArticulationAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLocalPos0Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLocalPos1Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLocalRot0Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLocalRot1Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBody0Rel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBody1Rel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBreakForceAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBreakTorqueAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollisionEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetExcludeFromArticulationAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLocalPos0Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLocalPos1Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLocalRot0Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLocalRot1Attr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class LimitAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateHighAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLowAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetHighAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLowAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPhysicsLimitAPIPath(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class MassAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateCenterOfMassAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateDensityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateDiagonalInertiaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateMassAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreatePrincipalAxesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCenterOfMassAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDensityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDiagonalInertiaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMassAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrincipalAxesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class MaterialAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateDensityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateDynamicFrictionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRestitutionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateStaticFrictionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDensityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDynamicFrictionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRestitutionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStaticFrictionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class MeshCollisionAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateApproximationAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetApproximationAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class PrismaticJoint(Joint, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLowerLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateUpperLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLowerLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUpperLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class RevoluteJoint(Joint, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLowerLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateUpperLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLowerLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUpperLimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class RigidBodyAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateAngularVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateKinematicEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRigidBodyEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateSimulationOwnerRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateStartsAsleepAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAngularVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetKinematicEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRigidBodyEnabledAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSimulationOwnerRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStartsAsleepAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVelocityAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class Scene(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateGravityDirectionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateGravityMagnitudeAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGravityDirectionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGravityMagnitudeAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class SphericalJoint(Joint, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateConeAngle0LimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateConeAngle1LimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetConeAngle0LimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetConeAngle1LimitAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class Tokens(Boost.Python.instance):
    acceleration = 'acceleration'
    angular = 'angular'
    boundingCube = 'boundingCube'
    boundingSphere = 'boundingSphere'
    colliders = 'colliders'
    convexDecomposition = 'convexDecomposition'
    convexHull = 'convexHull'
    distance = 'distance'
    drive = 'drive'
    force = 'force'
    kilogramsPerUnit = 'kilogramsPerUnit'
    limit = 'limit'
    linear = 'linear'
    meshSimplification = 'meshSimplification'
    none = 'none'
    physicsAngularVelocity = 'physics:angularVelocity'
    physicsApproximation = 'physics:approximation'
    physicsAxis = 'physics:axis'
    physicsBody0 = 'physics:body0'
    physicsBody1 = 'physics:body1'
    physicsBreakForce = 'physics:breakForce'
    physicsBreakTorque = 'physics:breakTorque'
    physicsCenterOfMass = 'physics:centerOfMass'
    physicsCollisionEnabled = 'physics:collisionEnabled'
    physicsConeAngle0Limit = 'physics:coneAngle0Limit'
    physicsConeAngle1Limit = 'physics:coneAngle1Limit'
    physicsDamping = 'physics:damping'
    physicsDensity = 'physics:density'
    physicsDiagonalInertia = 'physics:diagonalInertia'
    physicsDynamicFriction = 'physics:dynamicFriction'
    physicsExcludeFromArticulation = 'physics:excludeFromArticulation'
    physicsFilteredGroups = 'physics:filteredGroups'
    physicsFilteredPairs = 'physics:filteredPairs'
    physicsGravityDirection = 'physics:gravityDirection'
    physicsGravityMagnitude = 'physics:gravityMagnitude'
    physicsHigh = 'physics:high'
    physicsJointEnabled = 'physics:jointEnabled'
    physicsKinematicEnabled = 'physics:kinematicEnabled'
    physicsLocalPos0 = 'physics:localPos0'
    physicsLocalPos1 = 'physics:localPos1'
    physicsLocalRot0 = 'physics:localRot0'
    physicsLocalRot1 = 'physics:localRot1'
    physicsLow = 'physics:low'
    physicsLowerLimit = 'physics:lowerLimit'
    physicsMass = 'physics:mass'
    physicsMaxDistance = 'physics:maxDistance'
    physicsMaxForce = 'physics:maxForce'
    physicsMinDistance = 'physics:minDistance'
    physicsPrincipalAxes = 'physics:principalAxes'
    physicsRestitution = 'physics:restitution'
    physicsRigidBodyEnabled = 'physics:rigidBodyEnabled'
    physicsSimulationOwner = 'physics:simulationOwner'
    physicsStartsAsleep = 'physics:startsAsleep'
    physicsStaticFriction = 'physics:staticFriction'
    physicsStiffness = 'physics:stiffness'
    physicsTargetPosition = 'physics:targetPosition'
    physicsTargetVelocity = 'physics:targetVelocity'
    physicsType = 'physics:type'
    physicsUpperLimit = 'physics:upperLimit'
    physicsVelocity = 'physics:velocity'
    rotX = 'rotX'
    rotY = 'rotY'
    rotZ = 'rotZ'
    transX = 'transX'
    transY = 'transY'
    transZ = 'transZ'
    x = 'X'
    y = 'Y'
    z = 'Z'
    pass
def GetStageKilogramsPerUnit(*args, **kwargs) -> None:
    pass
def SetStageKilogramsPerUnit(*args, **kwargs) -> None:
    pass
def StageHasAuthoredKilogramsPerUnit(*args, **kwargs) -> None:
    pass
__MFB_FULL_PACKAGE_NAME = 'usdPhysics'
