[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Manufacturing Schema Extension for USD" 
description="Enables Manufacturing and Factory Planning related USD primitives"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/hendrikunger/Manufacturing-Schema-for-USD"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["usd", "schema"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides
[[python.module]]
name = "usd.schema.manufacturing"

[[python.module]]
name = "pxr.UsdManufacturing"

[[native.library]]
path = "bin/${lib_prefix}usdPhysics${lib_ext}"